-- CREATION OF SCHEMA

-- TABLE T_AREA
CREATE TABLE T_AREA(
AR_ID BIGINT NOT NULL,
AR_NAME VARCHAR(200) NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(AR_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_AREA.AR_ID IS 'ID area';
COMMENT ON COLUMN T_AREA.AR_NAME IS 'Name of the area';
COMMENT ON COLUMN T_AREA.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_AREA.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_AREA ADD CONSTRAINT U_AREA_NAME UNIQUE(AR_NAME);
-- SEQUENCE
CREATE SEQUENCE AREA_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
 

-- TABLE T_CATEGORY
CREATE TABLE T_CATEGORY(
CA_ID BIGINT NOT NULL,
CA_NAME VARCHAR(200) NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(CA_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_CATEGORY.CA_ID IS 'ID of the category';
COMMENT ON COLUMN T_CATEGORY.CA_NAME IS 'Name of the category';
COMMENT ON COLUMN T_CATEGORY.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_CATEGORY.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_CATEGORY ADD CONSTRAINT U_CATEGORY_NAME UNIQUE(CA_NAME);
-- SEQUENCE
CREATE SEQUENCE CATEGORY_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
  
-- TABLE T_DEPARTMENT
CREATE TABLE T_DEPARTMENT(
DE_ID BIGINT NOT NULL,
DE_NAME VARCHAR(200) NOT NULL,
DE_AREA_ID BIGINT,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(DE_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_DEPARTMENT.DE_ID IS 'ID of the department';
COMMENT ON COLUMN T_DEPARTMENT.DE_NAME IS 'Name of the department';
COMMENT ON COLUMN T_DEPARTMENT.DE_AREA_ID IS 'ID of the area';
COMMENT ON COLUMN T_DEPARTMENT.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_DEPARTMENT.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_DEPARTMENT ADD CONSTRAINT U_DE_NAME UNIQUE(DE_NAME);
ALTER TABLE T_DEPARTMENT ADD CONSTRAINT FK_DE_AREA_ID FOREIGN KEY(DE_AREA_ID) REFERENCES T_AREA(AR_ID);
-- SEQUENCE
CREATE SEQUENCE DEPARTMENT_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
-- TABLE T_CITY
CREATE TABLE T_CITY(
	CI_ID BIGINT NOT NULL,
	CI_ZIP VARCHAR(10) NOT NULL,
	CI_NAME VARCHAR(200) NOT NULL,
	CI_DEPARTMENT_ID BIGINT,
	CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
	UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
	PRIMARY KEY(CI_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_CITY.CI_ID IS 'ID of the city';
COMMENT ON COLUMN T_CITY.CI_ZIP IS 'Zip code of the city';
COMMENT ON COLUMN T_CITY.CI_NAME IS 'Name of the city';
COMMENT ON COLUMN T_CITY.CI_DEPARTMENT_ID IS 'Departement of the city';
COMMENT ON COLUMN T_CITY.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_CITY.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_CITY ADD CONSTRAINT U_CITY_ZIP UNIQUE(CI_ZIP);
ALTER TABLE T_CITY ADD CONSTRAINT U_CITY_NAME UNIQUE(CI_NAME);
ALTER TABLE T_CITY ADD CONSTRAINT FK_CI_DEPARTMENT_ID FOREIGN KEY(CI_DEPARTMENT_ID) REFERENCES T_DEPARTMENT(DE_ID);
-- SEQUENCE
CREATE SEQUENCE CITY_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
-- TABLE T_ROLE
CREATE TABLE T_ROLE(
RO_ID BIGINT NOT NULL,
RO_CODE VARCHAR(50),
RO_NAME VARCHAR(255),
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(RO_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_ROLE.RO_ID IS 'ID of the role';
COMMENT ON COLUMN T_ROLE.RO_CODE IS 'Code of the role';
COMMENT ON COLUMN T_ROLE.RO_NAME IS 'Label of the role';
COMMENT ON COLUMN T_ROLE.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_ROLE.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_ROLE ADD CONSTRAINT U_ROLE_CODE UNIQUE(RO_CODE);
-- SEQUENCE
CREATE SEQUENCE ROLE_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  

-- TABLE T_FUNCTION
CREATE TABLE T_FUNCTION(
FU_ID BIGINT NOT NULL,
FU_CODE VARCHAR(50),
FU_NAME VARCHAR(255),
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(FU_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_FUNCTION.FU_ID IS 'ID of the function';
COMMENT ON COLUMN T_FUNCTION.FU_CODE IS 'Code of the function';
COMMENT ON COLUMN T_FUNCTION.FU_NAME IS 'Label of the function';
COMMENT ON COLUMN T_FUNCTION.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_FUNCTION.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_FUNCTION ADD CONSTRAINT U_FONCTION_CODE UNIQUE(FU_CODE);
-- SEQUENCE
CREATE SEQUENCE FUNCTION_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;

  
-- TABLE T_ROLE_FONCTION
CREATE TABLE T_ROLE_FUNCTION(
RO_ID BIGINT NOT NULL,
FU_ID BIGINT NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(RO_ID,FU_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_ROLE_FUNCTION.RO_ID IS 'ID of the role';
COMMENT ON COLUMN T_ROLE_FUNCTION.FU_ID IS 'ID of the function';
-- CONSTRAINTS
ALTER TABLE T_ROLE_FUNCTION ADD CONSTRAINT FK_RO_ID FOREIGN KEY(RO_ID) REFERENCES T_ROLE(RO_ID);
ALTER TABLE T_ROLE_FUNCTION ADD CONSTRAINT FK_FU_ID FOREIGN KEY(FU_ID) REFERENCES T_FUNCTION(FU_ID);


-- TABLE T_MANAGER
CREATE TABLE T_MANAGER(
MA_ID BIGINT NOT NULL,
MA_LOGIN VARCHAR(8) NOT NULL,
MA_NAME VARCHAR(250) NOT NULL,
MA_FIRST_NAME VARCHAR(250) NOT NULL,
MA_MAIL VARCHAR(250),
MA_SALT VARCHAR(250),
MA_PASSWORD VARCHAR (250),
MA_PHONE VARCHAR(50),
MA_CHANGE_PASSWORD boolean,
MA_FROZ_ACCOUNT boolean,
MA_FROZ_DATE TIMESTAMP,
MA_ORIGIN_FROZ_MSG TEXT,
MA_LAST_ERROR_CONNEXION_DATE TIMESTAMP,
MA_ROLE_ID BIGINT,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(MA_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_MANAGER.MA_ID IS 'ID of the user';
COMMENT ON COLUMN T_MANAGER.MA_LOGIN IS 'Login of the user';
COMMENT ON COLUMN T_MANAGER.MA_NAME IS 'Name of the user';
COMMENT ON COLUMN T_MANAGER.MA_FIRST_NAME IS 'First name of the user';
COMMENT ON COLUMN T_MANAGER.MA_MAIL IS 'Mail of the user';
COMMENT ON COLUMN T_MANAGER.MA_SALT IS 'Salt of control';
COMMENT ON COLUMN T_MANAGER.MA_PASSWORD IS 'Password of the user';
COMMENT ON COLUMN T_MANAGER.MA_PHONE IS 'Phone number of the user';
COMMENT ON COLUMN T_MANAGER.MA_CHANGE_PASSWORD IS 'Boolean to force to change the password.0-False, 1-True';
COMMENT ON COLUMN T_MANAGER.MA_FROZ_ACCOUNT IS 'Boolean to lock/unlock the account.0-False, 1-True';
COMMENT ON COLUMN T_MANAGER.MA_FROZ_DATE IS 'Date of suspend of the account';
COMMENT ON COLUMN T_MANAGER.MA_ORIGIN_FROZ_MSG IS 'Reason of suspend of the account';
COMMENT ON COLUMN T_MANAGER.MA_LAST_ERROR_CONNEXION_DATE IS 'Last connection failure.';
COMMENT ON COLUMN T_MANAGER.MA_ROLE_ID IS 'ID role of the user';
COMMENT ON COLUMN T_MANAGER.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_MANAGER.UP_DATE IS 'Update date';

-- CONSTRAINTS
ALTER TABLE T_MANAGER ADD CONSTRAINT U_MANAGER_LOGIN UNIQUE(MA_LOGIN);
ALTER TABLE T_MANAGER ADD CONSTRAINT U_MANAGER_MAIL UNIQUE(MA_MAIL);
ALTER TABLE T_MANAGER ADD CONSTRAINT U_MANAGER_PASSWORD UNIQUE(MA_PASSWORD);
ALTER TABLE T_MANAGER ADD CONSTRAINT U_MANAGER_SALT UNIQUE(MA_SALT);
ALTER TABLE T_MANAGER ADD CONSTRAINT FK_MA_ROLE_ID FOREIGN KEY(MA_ROLE_ID) REFERENCES T_ROLE(RO_ID);
-- SEQUENCE
CREATE SEQUENCE MANAGER_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
  
-- TABLE T_CUSTOMER
CREATE TABLE T_CUSTOMER(
CU_ID BIGINT NOT NULL,
CU_NAME VARCHAR(250) NOT NULL,
CU_FIRST_NAME VARCHAR(250) NOT NULL,
CU_MAIL VARCHAR(250) NOT NULL,
CU_SALT VARCHAR(250),
CU_PASSWORD VARCHAR (250),
CU_PHONE VARCHAR(50),
CU_CHANGE_PASSWORD boolean,
CU_FROZEN_ACCOUNT boolean,
CU_FROZEN_DATE TIMESTAMP,
CU_ORIGIN_FROZEN_MSG TEXT,
CU_ROLE_ID BIGINT NOT NULL,
CU_LAST_FAILURE_CONNEXION_DATE TIMESTAMP,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(CU_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_CUSTOMER.CU_ID IS 'ID of the customer';
COMMENT ON COLUMN T_CUSTOMER.CU_NAME IS 'Name of the customer';
COMMENT ON COLUMN T_CUSTOMER.CU_FIRST_NAME IS 'First name of the customer';
COMMENT ON COLUMN T_CUSTOMER.CU_MAIL IS 'Mail of the customer';
COMMENT ON COLUMN T_CUSTOMER.CU_SALT IS 'Salt of control';
COMMENT ON COLUMN T_CUSTOMER.CU_PASSWORD IS 'Password of the customer';
COMMENT ON COLUMN T_CUSTOMER.CU_PHONE IS 'Phone number of the customer';
COMMENT ON COLUMN T_CUSTOMER.CU_CHANGE_PASSWORD IS 'Boolean to force to change the password.0-False, 1-True';
COMMENT ON COLUMN T_CUSTOMER.CU_FROZEN_ACCOUNT IS 'Boolean to lock/unlock the account.0-False, 1-True';
COMMENT ON COLUMN T_CUSTOMER.CU_FROZEN_DATE IS 'Date of suspend of the account';
COMMENT ON COLUMN T_CUSTOMER.CU_ORIGIN_FROZEN_MSG IS 'Reason of suspend of the account';
COMMENT ON COLUMN T_CUSTOMER.CU_LAST_FAILURE_CONNEXION_DATE IS 'Last connection failure.';
COMMENT ON COLUMN T_CUSTOMER.CU_ROLE_ID IS 'ID role of the customer';
COMMENT ON COLUMN T_CUSTOMER.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_CUSTOMER.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_CUSTOMER ADD CONSTRAINT U_CUSTOMER_MAIL UNIQUE(CU_MAIL);
ALTER TABLE T_CUSTOMER ADD CONSTRAINT U_CUSTOMER_PASSWORD UNIQUE(CU_PASSWORD);
ALTER TABLE T_CUSTOMER ADD CONSTRAINT U_CUSTOMER_SALT UNIQUE(CU_SALT);
ALTER TABLE T_CUSTOMER ADD CONSTRAINT FK_CU_ROLE_ID FOREIGN KEY(CU_ROLE_ID) REFERENCES T_ROLE(RO_ID);
-- SEQUENCE
CREATE SEQUENCE CUSTOMER_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
  

-- TABLE T_TOKEN
CREATE TABLE T_TOKEN(
TT_ID BIGINT NOT NULL,
TT_ACCESS_TOKEN VARCHAR(255) NOT NULL,
TT_EXPIRATION_DATE TIMESTAMP,
TT_CUSTOMER_ID BIGINT NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(TT_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_TOKEN.TT_ID IS 'ID of the token';
COMMENT ON COLUMN T_TOKEN.TT_ACCESS_TOKEN IS 'Value (GUID) of the token';
COMMENT ON COLUMN T_TOKEN.TT_EXPIRATION_DATE IS 'Expiration date of the token';
COMMENT ON COLUMN T_TOKEN.TT_CUSTOMER_ID IS 'ID of the customer';
COMMENT ON COLUMN T_TOKEN.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_TOKEN.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_TOKEN ADD CONSTRAINT U_TOKEN_ACCESS_TOKEN UNIQUE(TT_ACCESS_TOKEN);
ALTER TABLE T_TOKEN ADD CONSTRAINT FK_TT_CUSTOMER_ID FOREIGN KEY(TT_CUSTOMER_ID) REFERENCES T_CUSTOMER(CU_ID);
-- SEQUENCE
CREATE SEQUENCE TOKEN_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
 
 -- TABLE T_LOG_API
CREATE TABLE T_LOG_API(
LA_ID BIGINT NOT NULL,
LA_CODE_API VARCHAR(100) NOT NULL,
LA_VERSION_API VARCHAR(10) NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(LA_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_LOG_API.LA_ID IS 'ID of the picture';
COMMENT ON COLUMN T_LOG_API.LA_CODE_API IS 'Code of the API';
COMMENT ON COLUMN T_LOG_API.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_LOG_API.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_LOG_API ADD CONSTRAINT U_LOG_API_CODE UNIQUE(LA_CODE_API);
-- SEQUENCE
CREATE SEQUENCE LOG_API_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;