-- Create Role for Customer
INSERT INTO T_ROLE(RO_ID, RO_CODE, RO_NAME) VALUES (nextval('ROLE_SEQ'),'ROLE_CUSTOMER','APPS_CUSTOMER');

-- Create Function for Customer
INSERT INTO T_FUNCTION(FU_ID, FU_CODE, FU_NAME) VALUES (nextval('FUNCTION_SEQ'),'FU_UPDATE_CUSTOMER','Update Customer');

-- Join role AND the function

INSERT INTO T_ROLE_FUNCTION(RO_ID, FU_ID) SELECT RO_ID, FU_ID FROM T_ROLE, T_FUNCTION WHERE RO_CODE='ROLE_CUSTOMER' AND FU_CODE='FU_UPDATE_CUSTOMER';