-- create tables we need to create advert

-- TABLE T_ADVERT
CREATE TABLE T_ADVERT(
AD_ID BIGINT NOT NULL,
AD_TITLE VARCHAR(50) NOT NULL,
AD_DESCRIPTION VARCHAR(250) NOT NULL,
AD_PRICE float8 NOT NULL,
AD_CUSTOMER_ID BIGINT NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(AD_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_ADVERT.AD_ID IS 'ID of the advert';
COMMENT ON COLUMN T_ADVERT.AD_TITLE IS 'Title of the advert';
COMMENT ON COLUMN T_ADVERT.AD_DESCRIPTION IS 'Descrption of the advert';
COMMENT ON COLUMN T_ADVERT.AD_PRICE IS 'Price of the advert';
COMMENT ON COLUMN T_ADVERT.AD_CUSTOMER_ID IS 'ID of the customer';
COMMENT ON COLUMN T_ADVERT.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_ADVERT.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_ADVERT ADD CONSTRAINT FK_AD_CUSTOMER_ID FOREIGN KEY(AD_CUSTOMER_ID) REFERENCES T_CUSTOMER(CU_ID);
-- SEQUENCE
CREATE SEQUENCE ADVERT_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;

  
-- TABLE T_PICTURE
CREATE TABLE T_PICTURE(
PI_ID BIGINT NOT NULL,
PI_NAME VARCHAR(100) NOT NULL,
PI_ADDRESS VARCHAR(250) NOT NULL,
PI_ADVERT_ID BIGINT NOT NULL,
CRE_DATE TIMESTAMP default CURRENT_TIMESTAMP,
UP_DATE TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(PI_ID)
);
-- COMMENTS ON COLUMNS
COMMENT ON COLUMN T_PICTURE.PI_ID IS 'ID of the picture';
COMMENT ON COLUMN T_PICTURE.PI_NAME IS 'Name of the picture';
COMMENT ON COLUMN T_PICTURE.PI_ADDRESS IS 'Address of the picture';
COMMENT ON COLUMN T_PICTURE.PI_ADVERT_ID IS 'ID of the advert';
COMMENT ON COLUMN T_PICTURE.CRE_DATE IS 'Date of creation';
COMMENT ON COLUMN T_PICTURE.UP_DATE IS 'Update date';
-- CONSTRAINTS
ALTER TABLE T_PICTURE ADD CONSTRAINT FK_PI_ADVERT_ID FOREIGN KEY(PI_ADVERT_ID) REFERENCES T_ADVERT(AD_ID);
-- SEQUENCE
CREATE SEQUENCE PICTURE_SEQ        
  INCREMENT 1                     
  MINVALUE 1                      
  MAXVALUE 9223372036854775807    
  START 1                         
  CACHE 1;
  
  
-- Create Function 
INSERT INTO T_FUNCTION(FU_ID, FU_CODE, FU_NAME) VALUES (nextval('FUNCTION_SEQ'),'FU_CREATE_ADVERT','Create Advert');

-- Join role AND the function
INSERT INTO T_ROLE_FUNCTION(RO_ID, FU_ID) SELECT RO_ID, FU_ID FROM T_ROLE, T_FUNCTION WHERE RO_CODE='ROLE_CUSTOMER' AND FU_CODE='FU_CREATE_ADVERT';